---  
- name: Install necessary packages for ruby installation
  apt: pkg={{ item }} state=installed
  with_items:
    - autoconf
    - automake
    - bison
    - build-essential
    - curl
    - exuberant-ctags
    - git-core
    - git
    - libreadline6
    - libreadline6-dev
    - libreadline-dev
    - libsqlite3-0
    - libsqlite3-dev
    - libssl-dev
    - libyaml-dev
    - libc6-dev
    - libncurses5-dev
    - libtool
    - libxml2-dev
    - libxslt1-dev
    - openssl
    - sqlite3
    - subversion
    - zlib1g
    - zlib1g-dev

- name: Installs rbenv
  git:
    repo: git://github.com/sstephenson/rbenv.git
    dest: "~{{ user }}/.rbenv"
  sudo: yes
  sudo_user: "{{ user }}"

- name: Ensure fragments bash dir exists
  command: "su {{ user }} -c bash -lc 'mkdir -p ~/.bash.d'"
  # file:
  #   dest: "/home/{{ user }}/.bash.d/"
  #   state: directory
  #   owner: "{{ user }}"
  #   group: "{{ user }}"
  # sudo: yes
  # sudo_user: "{{ user }}"

- name: Installs rbenv bash file
  copy:
    src: 50_rbenv.bash
    dest: "~{{ user }}/.bash.d/50_rbenv.bash"
    mode: 700
    owner: "{{ user }}"

- name: Source rbenv bash file in dot bashrc
  lineinfile:
    dest: "~{{ user }}/.bash_profile"
    regexp: "rbenv"
    insertafter: EOF
    line: "source ~/.bash.d/50_rbenv.bash"
    create: yes
  sudo: yes
  sudo_user: "{{ user }}"

- name: Source rbenv bash file in dot bashrc
  lineinfile:
    dest: "~{{ user }}/.bashrc"
    regexp: "rbenv"
    insertafter: EOF
    line: "source ~/.bash.d/50_rbenv.bash"
    create: yes
  sudo: yes
  sudo_user: webmaster

- name: Creates plugin directory
  file:
    path: "~{{ user }}/.rbenv/plugins/"
    owner: "{{ user }}"
    mode: 0755
    state: directory

- name: Installs ruby-build
  git:
    repo: git://github.com/sstephenson/ruby-build.git
    dest: "~{{ user }}/.rbenv/plugins/ruby-build"
  sudo: yes
  sudo_user: "{{ user }}"

- name: Adds .gemrc
  copy:
    src: gemrc
    dest: "~{{ user }}/.gemrc"
    owner: "{{ user }}"
    mode: 0750

- name: "Checks ruby is installed"
  command: "su {{ user }} -c bash -lc 'rbenv versions | grep {{ ruby_version }}'"
  register: ruby_installed
  ignore_errors: yes

- name: Installs ruby
  command: "su {{ user }} -c bash -lc 'CONFIGURE_OPTS=--disable-install-rdoc rbenv install {{ ruby_version }}'"
  async: 600
  poll: 30
  when: ruby_installed|failed

- name: "Checks if bundler is installed"
  command: "su {{ user }} -c bash -lc 'rbenv global {{ ruby_version }} && rbenv rehash && gem list | grep bundler'"
  register: bundler_installed
  ignore_errors: yes

- name: "Install bundler"
  command: "su {{ user }} -c bash -lc 'rbenv global {{ ruby_version }} && rbenv rehash && gem install bundler'"
  when: bundler_installed|failed